services:
  smartfin_data_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: smartfin_data_api
    deploy:
      resources:
        limits:
          memory: 4G
    labels:
      caddy: data.smartfin.e4e.ucsd.edu
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy_proxy
      - default
  postgres:
    image: postgres:16.4
    restart: always
    shm_size: 128 mb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_admin_password
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/:rw
      - ./postgres/config/:/etc/postgresql/:ro
      # - ./.secrets/certs/:/certs/:ro
      - ./postgres/scripts/:/docker-entrypoint-initdb.d/:ro
      - /etc/passwd:/etc/passwd:ro
    secrets:
      - postgres_admin_password
    command: --config_file=/etc/postgresql/postgres.conf
    # ports:
    #   - 5432:5432
    user: "${USER_ID}:${GROUP_ID}"

secrets:
  postgres_admin_password: 
    file: .secrets/postgres_admin_password.txt

networks:
  caddy_proxy:
   external: true