name: pytest

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Set test env vars
      run: |
        echo "E4EFS_POSTGRES__USERNAME=postgres" >> "$GITHUB_ENV"
        echo "E4EFS_POSTGRES__HOST=localhost" >> "$GITHUB_ENV"
        echo "E4EFS_POSTGRES__PASSWORD_FILE=./README.md" >> "$GITHUB_ENV"
        echo "E4EFS_EXIFTOOL__PATH=./README.md" >> "$GITHUB_ENV"
    # - name: Test
    #   run: |
    #     coverage run -m pytest tests
    # - name: Generate Report
    #   run: |
    #     coverage html
    # - name: Upload report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: coverage-report
    #     path: htmlcov/*